# Generated by Django 5.2.17 on 2026-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_departamento_alter_linkutil_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='deve_trocar_senha',
            field=models.BooleanField(default=False),
        ),
    ]
