# Generated by Django 5.2.17 on 2026-08-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_funcionario_deve_trocar_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferramenta',
            options={'ordering': ('nome',), 'verbose_name': 'Ferramenta / Recurso', 'verbose_name_plural': 'Ferramentas / Recursos'},
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='ferramentas/'),
        ),
        migrations.AddField(
            model_name='linkutil',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='links_uteis/'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='linkutil',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
