# Generated by Django 5.2.17 on 2026-08-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_ferramenta_options_ferramenta_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferramenta',
            options={'ordering': ('nome',), 'verbose_name': 'Ferramenta / Recurso', 'verbose_name_plural': 'Links/Arquivos Centro de Custos'},
        ),
        migrations.AlterModelOptions(
            name='linkutil',
            options={'ordering': ('nome',), 'verbose_name': 'Links Colaboradores', 'verbose_name_plural': 'Links/Arquivos Colaboradores'},
        ),
    ]
