# Generated by Django 5.2.17 on 2026-08-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_ferramenta_options_alter_linkutil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tentativas_falhas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
