# Generated by Django 6.1 on 2026-08-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_funcionario_bloqueado_ate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='vinculado_ad',
            field=models.BooleanField(default=False, help_text='Quando marcado, o login é autenticado no Active Directory em vez da senha local.', verbose_name='Vinculado ao Active Directory'),
        ),
    ]
