# Generated by Django 6.1 on 2026-08-31 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_funcionario_vinculado_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('grupo_sistema', models.BooleanField(default=False, editable=False, help_text='Marca grupos internos protegidos contra exclusão/renomeação.')),
            ],
            options={
                'verbose_name': 'Grupo/Espaço',
                'verbose_name_plural': 'Grupos/Espaços',
                'ordering': ('nome',),
            },
        ),
        migrations.AlterModelOptions(
            name='ferramenta',
            options={'ordering': ('nome',), 'verbose_name': 'Ferramenta / Recurso', 'verbose_name_plural': 'Ferramentas / Recursos'},
        ),
        migrations.AlterModelOptions(
            name='linkutil',
            options={'ordering': ('nome',), 'verbose_name': 'Link legado', 'verbose_name_plural': 'Links legados'},
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='centro_custo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramentas', to='usuarios.centrocusto'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='ferramentas', to='usuarios.grupoespaco', verbose_name='Grupos/Espaços'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='usuarios.grupoespaco', verbose_name='Grupos/Espaços'),
        ),
        migrations.AddField(
            model_name='linkutil',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='links_uteis', to='usuarios.grupoespaco', verbose_name='Grupos/Espaços'),
        ),
    ]
