# Generated by Django 6.1 on 2026-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_grupoespaco_alter_ferramenta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='icone',
            field=models.CharField(blank=True, choices=[('link', 'Link'), ('globe', 'Site / Internet'), ('document', 'Documento'), ('folder', 'Pasta / Arquivos'), ('chart', 'Gráfico / Relatórios'), ('computer', 'Sistema / Aplicação'), ('database', 'Banco de dados'), ('email', 'E-mail'), ('users', 'Usuários'), ('support', 'Suporte'), ('shield', 'Segurança'), ('settings', 'Configurações')], default='', max_length=30, verbose_name='Ícone'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ferramentas/logos/', verbose_name='Logo personalizada'),
        ),
        migrations.AddField(
            model_name='linkutil',
            name='icone',
            field=models.CharField(blank=True, choices=[('link', 'Link'), ('globe', 'Site / Internet'), ('document', 'Documento'), ('folder', 'Pasta / Arquivos'), ('chart', 'Gráfico / Relatórios'), ('computer', 'Sistema / Aplicação'), ('database', 'Banco de dados'), ('email', 'E-mail'), ('users', 'Usuários'), ('support', 'Suporte'), ('shield', 'Segurança'), ('settings', 'Configurações')], default='', max_length=30, verbose_name='Ícone'),
        ),
        migrations.AddField(
            model_name='linkutil',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='links_uteis/logos/', verbose_name='Logo personalizada'),
        ),
    ]
