# Generated by Django 6.1 on 2026-09-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_ferramenta_icone_ferramenta_logo_linkutil_icone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramenta',
            name='centro_custo',
        ),
        migrations.DeleteModel(
            name='LinkUtil',
        ),
    ]
