# Generated by Django 6.1 on 2026-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_ferramenta_centro_custo_delete_linkutil'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição / Mensagem')),
                ('tag', models.CharField(default='Comunicado', max_length=50, verbose_name='Tag/Categoria')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagem de Fundo')),
                ('link_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Destino (Opcional)')),
                ('link_texto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto do Botão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Banner Informativo',
                'verbose_name_plural': 'Banners Informativos',
                'ordering': ('ordem', 'titulo'),
            },
        ),
    ]
