# Generated by Django 6.1 on 2026-09-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_bannerinformativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinformativo',
            options={'ordering': ('ordem',), 'verbose_name': 'Banner Informativo', 'verbose_name_plural': 'Banners Informativos'},
        ),
        migrations.RemoveField(
            model_name='bannerinformativo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='bannerinformativo',
            name='link_texto',
        ),
        migrations.RemoveField(
            model_name='bannerinformativo',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='bannerinformativo',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='bannerinformativo',
            name='titulo',
        ),
    ]
