# Generated by Django 6.1 on 2026-09-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_bannerinformativo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinformativo',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Redirecionamento ao Clicar'),
        ),
    ]
