# Generated by Django 6.1 on 2026-09-08 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_bannerinformativo_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinformativo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerinformativo',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='banners/', verbose_name='Imagem de Fundo'),
            preserve_default=False,
        ),
    ]
