# Generated by Django 6.1 on 2026-09-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_bannerinformativo_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinformativo',
            name='data_criacao',
        ),
    ]
