# Generated by Django 6.1 on 2026-09-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_remove_bannerinformativo_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinformativo',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início da Exibição'),
        ),
        migrations.AddField(
            model_name='bannerinformativo',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Término da Exibição'),
        ),
    ]
